import React, { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button } from '../components/common';
import { useSession } from '../session';
import { getItem } from '../storage';
import { colors, radius } from '../theme';
const PHONE_PATTERN=/^1[3-9]\d{9}$/;

export default function PhoneLoginScreen(){
  const {sendSmsCode,loginWithSms,loginWithPassword}=useSession();
  const [mode,setMode]=useState<'password'|'sms'>('password'); const [phone,setPhone]=useState(''); const [password,setPassword]=useState(''); const [code,setCode]=useState('');
  const [countdown,setCountdown]=useState(0); const [sending,setSending]=useState(false); const [loggingIn,setLoggingIn]=useState(false);
  useEffect(()=>{getItem('lastLoginPhone').then(v=>v&&setPhone(v));},[]);
  useEffect(()=>{if(countdown<=0)return;const timer=setInterval(()=>setCountdown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer);},[countdown]);
  const normalized=phone.replace(/\D/g,''); const phoneValid=PHONE_PATTERN.test(normalized);
  const send=async()=>{if(!phoneValid)return Alert.alert('提示','请输入正确的11位手机号');setSending(true);try{setCountdown(await sendSmsCode(normalized));Alert.alert('验证码已发送',`短信已发送至 ${normalized.slice(0,3)}****${normalized.slice(7)}`);}catch(e){Alert.alert('发送失败',e instanceof Error?e.message:'请稍后重试');}finally{setSending(false)}};
  const submit=async()=>{if(!phoneValid)return Alert.alert('提示','请输入正确的11位手机号');if(mode==='password'&&!password)return Alert.alert('提示','请输入密码');if(mode==='sms'&&!/^\d{6}$/.test(code))return Alert.alert('提示','请输入6位验证码');setLoggingIn(true);try{if(mode==='password')await loginWithPassword(normalized,password);else await loginWithSms(normalized,code);}catch(e){Alert.alert('登录失败',e instanceof Error?e.message:'请稍后重试');}finally{setLoggingIn(false)}};
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
    <View style={styles.brand}><View style={styles.logo}><Text style={styles.logoText}>联</Text></View><Text style={styles.title}>全球云智算</Text><Text style={styles.subtitle}>登录后管理设备与查看收益</Text></View>
    <View style={styles.card}><View style={styles.tabs}><Pressable style={[styles.tab,mode==='password'&&styles.tabActive]} onPress={()=>setMode('password')}><Text style={[styles.tabText,mode==='password'&&styles.tabTextActive]}>密码登录</Text></Pressable><Pressable style={[styles.tab,mode==='sms'&&styles.tabActive]} onPress={()=>setMode('sms')}><Text style={[styles.tabText,mode==='sms'&&styles.tabTextActive]}>短信登录</Text></Pressable></View>
      <Text style={styles.label}>手机号码</Text><View style={styles.inputRow}><Text style={styles.country}>+86</Text><View style={styles.divider}/><TextInput value={phone} onChangeText={v=>setPhone(v.replace(/\D/g,'').slice(0,11))} placeholder="请输入手机号" keyboardType="phone-pad" maxLength={11} style={styles.input}/></View>
      {mode==='password'?<><Text style={styles.label}>登录密码</Text><View style={styles.inputRow}><TextInput value={password} onChangeText={setPassword} placeholder="请输入密码" secureTextEntry autoCapitalize="none" style={styles.input}/></View></>:<><Text style={styles.label}>短信验证码</Text><View style={styles.inputRow}><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} placeholder="请输入6位验证码" keyboardType="number-pad" maxLength={6} style={styles.input}/><Pressable disabled={!phoneValid||sending||countdown>0} onPress={send} style={styles.send}><Text style={styles.sendText}>{sending?'发送中':countdown>0?`${countdown}秒`:'获取验证码'}</Text></Pressable></View></>}
      <Button title={loggingIn?'登录中...':'登录'} onPress={submit} disabled={loggingIn} style={styles.login}/><Text style={styles.tip}>账号由管理员开通；首次登录后必须修改临时密码</Text>
    </View></ScrollView></KeyboardAvoidingView>;
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.bg},content:{flexGrow:1,justifyContent:'center',padding:24,paddingBottom:40},brand:{alignItems:'center',marginBottom:28},logo:{width:68,height:68,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:colors.navy,borderWidth:3,borderColor:'#d8f6fb'},logoText:{color:colors.cyan,fontSize:30,fontWeight:'900'},title:{marginTop:14,fontSize:27,fontWeight:'900',color:colors.navy,letterSpacing:2},subtitle:{marginTop:8,fontSize:14,color:colors.textSecondary},card:{backgroundColor:colors.card,borderRadius:radius.xl,padding:20,borderWidth:1,borderColor:colors.border},tabs:{flexDirection:'row',marginBottom:22,backgroundColor:'#f2f5f8',borderRadius:radius.md,padding:4},tab:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:radius.md},tabActive:{backgroundColor:colors.navy},tabText:{fontWeight:'700',color:colors.textSecondary},tabTextActive:{color:'#fff'},label:{color:colors.textSecondary,fontSize:13,fontWeight:'600',marginBottom:8},inputRow:{minHeight:50,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:'#fbfdff',marginBottom:16,overflow:'hidden'},country:{paddingHorizontal:14,fontWeight:'700',color:colors.text},divider:{width:StyleSheet.hairlineWidth,height:22,backgroundColor:colors.border},input:{flex:1,minHeight:48,paddingHorizontal:14,color:colors.text,fontSize:16},send:{height:48,paddingHorizontal:16,justifyContent:'center',borderLeftWidth:StyleSheet.hairlineWidth,borderColor:colors.border,backgroundColor:'#eef7ff'},sendText:{color:colors.primary,fontWeight:'700',fontSize:13},login:{marginTop:6,minHeight:48},tip:{textAlign:'center',color:colors.muted,fontSize:12,marginTop:14}});
